/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_Mp3Encoder
#define _Included_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL com_lzx_record_LameManager_version
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL com_lzx_record_LameManager_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

JNIEXPORT jint JNICALL com_lzx_record_LameManager_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

JNIEXPORT jint JNICALL com_lzx_record_LameManager_encodeInterleaved
      (JNIEnv *, jclass, jshortArray, jint, jbyteArray);

JNIEXPORT jint JNICALL com_lzx_record_LameManager_encodeByByte
      (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jbyteArray);

JNIEXPORT jint JNICALL com_lzx_record_LameManager_flush
  (JNIEnv *, jclass, jbyteArray);

JNIEXPORT void JNICALL com_lzx_record_LameManager_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
